- name: AttackBox initial setup
  hosts: localhost
  connection: local
  roles:
    - role: init
    - role: wm
    - role: dm
    - role: fonts
    - role: alacritty
    - role: zsh
      tags: zsh_role
    - role: tools
      tags: tools_role
    - role: pentools
      tags: pentools_role
    - role: vbox_guest
      tags: vbox_role