- name: AttackBox initial setup
  hosts: localhost
  connection: local
  roles:
    - role: init
    - role: vbox_guest
    - role: wm
    - role: dm
    # - role: fonts
    # - role: alacritty
    # - role: zsh
    #   tags: zsh_role