- name: Install zsh and plugins
  become: true
  ansible.builtin.apt:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting

- name: Create ~/.zshrc
  copy:
    src: "{{ playbook_dir }}/roles/zsh/files/.zshrc"
    dest: "{{ ansible_env.HOME }}/"
    mode: 0644