- name: Install zsh and plugins
  become: true
  ansible.builtin.apt:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting

- name: Create ~/.zshrc
  copy:
    src: "{{ playbook_dir }}/roles/zsh/files/.zshrc"
    dest: "{{ ansible_env.HOME }}/"
    mode: 0644

- name: Change shell for user
  become: true
  ansible.builtin.shell: usermod --shell /bin/zsh {{ ansible_env.USER }}
