- name: Install ly requirements
  become: true
  ansible.builtin.apt:
    name:
      - libpam0g-dev
      - libxcb-xkb-dev

- name: Download ly
  become: true
  ansible.builtin.git:
    repo: https://github.com/fairyglade/ly
    dest: /usr/local/src/ly

- name: Make ly
  become: true
  ansible.builtin.make:
    chdir: /usr/local/src/ly
    target: installsystemd

- name: Enable ly
  become: true
  ansible.builtin.systemd_service:
    name: ly.service
    enabled: true