- name: Install ly requirements
  become: true
  ansible.builtin.apt:
    name:
      - libpam0g-dev
      - libxcb-xkb-dev

- name: Download ly
  become: true
  ansible.builtin.git:
    repo: https://github.com/fairyglade/ly
    dest: /usr/local/src/ly
    recursive: yes

- name: Make ly
  become: true
  ansible.builtin.shell: |
    cd /usr/local/src/ly
    make
    make install installsystemd
    systemctl enable ly.service