- name: Nmap
  tags: nmap
  become: true
  ansible.builtin.apt:
    name: nmap

- name: NetExec
  tags: netexec
  ansible.builtin.shell: pipx install git+https://github.com/Pennyw0rth/NetExec

- name: Find latest ffuf
  tags: ffuf
  uri:
    url: https://api.github.com/repos/ffuf/ffuf/releases/latest
    return_content: true
  register: fuff_latest

- name: Install ffuf
  tags: ffuf
  loop: "{{ fuff_latest.json.assets }}"
  when: "'linux_amd64.tar.gz' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    keep_newer: yes
    include: ffuf

- name: Find latest gobuster
  tags: gobuster
  uri:
    url: https://api.github.com/repos/OJ/gobuster/releases/latest
    return_content: true
  register: gobuster_latest

- name: Install gobuster
  tags: gobuster
  loop: "{{ gobuster_latest.json.assets }}"
  when: "'Linux_x86_64.tar.gz' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    keep_newer: yes
    include: gobuster

- name: BloodHound
  tags: bloodhound
  uri:
    url: https://api.github.com/repos/BloodHoundAD/BloodHound/releases/latest
    return_content: true
  register: bloodhound_latest

- name: Install BloodHound
  tags: bloodhound
  loop: "{{ bloodhound_latest.json.assets }}"
  when: "'linux-x64.zip' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/"
    keep_newer: yes
  
- name: Rename BloodHound directory and create symlink
  tags: bloodhound
  ansible.builtin.shell: |
    mv {{ ansible_env.HOME }}/.local/BloodHound* {{ ansible_env.HOME }}/.local/bloodhound
    ln -s {{ ansible_env.HOME }}/.local/bin/bloodhound {{ ansible_env.HOME }}/.local/bloodhound/BloodHound