- name: Nmap
  tags: nmap
  become: true
  ansible.builtin.apt:
    name: nmap

- name: Proxychains4
  tags: proxychains4
  become: true
  ansible.builtin.apt:
    name: proxychains4

- name: Freerdp
  tags: freerdp
  become: true
  ansible.builtin.apt:
    name: freerdp2-x11

- name: Smbclient
  tags: smbclient
  become: true
  ansible.builtin.apt:
    name: smbclient

- name: FTP
  tags: ftp
  become: true
  ansible.builtin.apt:
    name: ftp

- name: Hydra
  tags: hydra
  become: true
  ansible.builtin.apt:
    name: hydra

- name: NetExec
  tags: netexec
  ansible.builtin.shell: pipx install git+https://github.com/Pennyw0rth/NetExec

- name: SmbMap
  tags: smbmap
  ansible.builtin.shell: pipx install smbmap

- name: VSCode
  tags: vscode
  become: true
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/docs/?dv=linux64_deb

### ffuf
- name: Find latest ffuf
  tags: ffuf
  uri:
    url: https://api.github.com/repos/ffuf/ffuf/releases/latest
    return_content: true
  register: fuff_latest

- name: Install ffuf
  tags: ffuf
  loop: "{{ fuff_latest.json.assets }}"
  when: "'linux_amd64.tar.gz' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    keep_newer: yes
    include: ffuf
###

### gobuster
- name: Find latest gobuster
  tags: gobuster
  uri:
    url: https://api.github.com/repos/OJ/gobuster/releases/latest
    return_content: true
  register: gobuster_latest

- name: Install gobuster
  tags: gobuster
  loop: "{{ gobuster_latest.json.assets }}"
  when: "'Linux_x86_64.tar.gz' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    keep_newer: yes
    include: gobuster
###

### bloodhound
- name: BloodHound
  tags: bloodhound
  uri:
    url: https://api.github.com/repos/BloodHoundAD/BloodHound/releases/latest
    return_content: true
  register: bloodhound_latest

- name: Install BloodHound
  tags: bloodhound
  loop: "{{ bloodhound_latest.json.assets }}"
  when: "'linux-x64.zip' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/"
    keep_newer: yes

- name: Rename BloodHound directory and create symlink
  tags: bloodhound
  ansible.builtin.shell: |
    mv {{ ansible_env.HOME }}/.local/BloodHound* {{ ansible_env.HOME }}/.local/bloodhound
    ln -s {{ ansible_env.HOME }}/.local/bloodhound/BloodHound {{ ansible_env.HOME }}/.local/bin/bloodhound
###

### chisel
- name: Chisel
  tags: chisel
  become: true
  ansible.builtin.shell: curl https://i.jpillora.com/chisel! | bash
###

### tun2socks
- name: Find latest tun2socks
  tags: tun2socks
  uri:
    url: https://api.github.com/repos/xjasonlyu/tun2socks/releases/latest
    return_content: true
  register: tun2socks_latest

- name: Install tun2socks
  tags: tun2socks
  loop: "{{ tun2socks_latest.json.assets }}"
  when: "'linux-amd64.zip' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    keep_newer: yes

- name: Rename tun2socks binary
  tags: tun2socks
  ansible.builtin.shell: mv {{ ansible_env.HOME }}/.local/bin/tun2socks* {{ ansible_env.HOME }}/.local/bin/tun2socks
###

