- name: Nmap
  tags: nmap
  become: true
  ansible.builtin.apt:
    name: nmap

- name: Proxychains4
  tags: proxychains4
  become: true
  ansible.builtin.apt:
    name: proxychains4

- name: Freerdp
  tags: freerdp
  become: true
  ansible.builtin.apt:
    name: freerdp2-x11

- name: Smbclient
  tags: smbclient
  become: true
  ansible.builtin.apt:
    name: smbclient

- name: FTP
  tags: ftp
  become: true
  ansible.builtin.apt:
    name: ftp

- name: Hydra
  tags: hydra
  become: true
  ansible.builtin.apt:
    name: hydra

- name: Rlwrap
  tags: rlwrap
  become: true
  ansible.builtin.apt:
    name: rlwrap

- name: VSCode
  tags: vscode
  become: true
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: NetExec
  tags: netexec
  ansible.builtin.shell: pipx install git+https://github.com/Pennyw0rth/NetExec

- name: DonPAPI
  tags: donpapi
  ansible.builtin.shell: pipx install git+https://github.com/login-securite/DonPAPI.git

- name: Wafw00f
  tags: wafw00f
  ansible.builtin.shell: pipx install git+https://github.com/EnableSecurity/wafw00f

- name: SmbMap
  tags: smbmap
  ansible.builtin.shell: pipx install smbmap

- name: Impacket
  tags: impacket
  ansible.builtin.shell: pipx install impacket

# https://github.com/darkoperator/dnsrecon/
- name: Dnsrecon
  tags: dnsrecon
  ansible.builtin.shell: pipx install dnsrecon

# https://github.com/Densaugeo/uploadserver
- name: Uploadserver
  tags: uploadserver
  ansible.builtin.shell: pipx install uploadserver

# https://github.com/bitsadmin/wesng
- name: Wesng
  tags: wesng
  ansible.builtin.shell: |
    pipx install git+https://github.com/bitsadmin/wesng
    pipx inject wesng chardet

# https://github.com/jpillora/chisel
- name: Chisel
  tags: chisel
  become: true
  ansible.builtin.shell: curl https://i.jpillora.com/chisel! | bash

# https://github.com/Hackplayers/evil-winrm
- name: EvilWinrm requirements
  tags: evilwinrm
  become: true
  ansible.builtin.apt:
    name:
      - ruby
      - ruby-dev

- name: Install EvilWinrm
  tags: evilwinrm
  become: true
  ansible.builtin.shell: gem install evil-winrm

# https://github.com/ffuf/ffuf
- name: Find latest ffuf
  tags: ffuf
  uri:
    url: https://api.github.com/repos/ffuf/ffuf/releases/latest
    return_content: true
  register: fuff_latest

- name: Install ffuf
  tags: ffuf
  loop: "{{ fuff_latest.json.assets }}"
  when: "'linux_amd64.tar.gz' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    keep_newer: yes
    include: ffuf

# https://github.com/OJ/gobuster
- name: Find latest gobuster
  tags: gobuster
  uri:
    url: https://api.github.com/repos/OJ/gobuster/releases/latest
    return_content: true
  register: gobuster_latest

- name: Install gobuster
  tags: gobuster
  loop: "{{ gobuster_latest.json.assets }}"
  when: "'Linux_x86_64.tar.gz' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    keep_newer: yes
    include: gobuster

# https://github.com/BloodHoundAD/BloodHound
- name: BloodHound
  tags: bloodhound
  uri:
    url: https://api.github.com/repos/BloodHoundAD/BloodHound/releases/latest
    return_content: true
  register: bloodhound_latest

- name: Install BloodHound
  tags: bloodhound
  loop: "{{ bloodhound_latest.json.assets }}"
  when: "'linux-x64.zip' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/"
    keep_newer: yes

- name: Rename BloodHound directory
  tags: bloodhound
  ansible.builtin.shell: |
    mv {{ ansible_env.HOME }}/.local/BloodHound* {{ ansible_env.HOME }}/.local/bloodhound

- name: Create dmenu launcher
  tags: bloodhound
  become: true
  copy:
    dest: "/usr/local/bin/bloodhound"
    content: |
      #!/bin/sh
      $HOME/.local/bloodhound/BloodHound --in-process-gpu  
    mode: 0755


# https://github.com/xjasonlyu/tun2socks
- name: Find latest tun2socks
  tags: tun2socks
  uri:
    url: https://api.github.com/repos/xjasonlyu/tun2socks/releases/latest
    return_content: true
  register: tun2socks_latest

- name: Install tun2socks
  tags: tun2socks
  loop: "{{ tun2socks_latest.json.assets }}"
  when: "'linux-amd64.zip' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    keep_newer: yes

- name: Rename tun2socks binary
  tags: tun2socks
  ansible.builtin.shell: mv {{ ansible_env.HOME }}/.local/bin/tun2socks* {{ ansible_env.HOME }}/.local/bin/tun2socks

# TODO:
# https://github.com/nil0x42/phpsploit
# https://github.com/lgandx/Responder
