- name: Appearence
  tags: appearence
  become: true
  ansible.builtin.apt:
    name:
      - papirus-icon-theme
      - gnome-themes-extra-data
      - lxappearance

- name: Openvpn
  tags: Openvpn
  become: true
  ansible.builtin.apt:
    name:
      - openvpn
      - network-manager-openvpn-gnome

- name: Wireguard
  tags: wireguard
  become: true
  ansible.builtin.apt:
    name: wireguard

- name: Firefox
  tags: firefox
  become: true
  ansible.builtin.apt:
    name: firefox-esr

- name: Configure firefox enterprise policy
  tags: firefox
  become: true
  ansible.builtin.shell: yes | unzip "{{ playbook_dir }}/roles/tools/files/enterprise_policy.zip" -d /usr/share/firefox-esr/

- name: Configure firefox profile
  tags: firefox
  ansible.builtin.shell: |
    cd ~/.mozilla/firefox/*.default-esr
    yes | rm -rf *
    yes | unzip "{{ playbook_dir }}/roles/tools/files/profile.zip" -d ~/.mozilla/firefox/*.default-esr/

- name: Thunar
  tags: thunar
  become: true
  ansible.builtin.apt:
    name:
      - thunar
      - file-roller

- name: Pipx + pip3
  tags: pipx
  become: true
  ansible.builtin.apt:
    name:
      - pipx
      - python3-pip

# https://github.com/sharkdp/bat
- name: Find latest bat
  tags: bat
  uri:
    url: https://api.github.com/repos/sharkdp/bat/releases/latest
    return_content: true
  register: bat_latest

- name: Install bat
  tags: bat
  become: true
  loop: "{{ bat_latest.json.assets }}"
  when: "'bat_*_amd64.deb' in item.name"
  ansible.builtin.apt:
    deb: "{{ item.browser_download_url }}"