- name: Appearence
  tags: appearence
  become: true
  ansible.builtin.apt:
    name:
      - papirus-icon-theme
      - lxappearance

- name: Openvpn
  tags: Openvpn
  become: true
  ansible.builtin.apt:
    name:
      - openvpn
      - network-manager-openvpn-gnome

- name: Wireguard
  tags: wireguard
  become: true
  ansible.builtin.apt:
    name: wireguard

- name: Firefox
  tags: Firefox
  become: true
  ansible.builtin.apt:
    name: firefox-esr