- name: Fixing time
  become: true
  ansible.builtin.shell: |
    timedatectl set-ntp off
    timedatectl set-ntp on

- name: Update and upgrade
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: yes

- name: Install essential tools
  become: true
  ansible.builtin.apt:
    name:
      - git
      - curl
      - unzip
      - build-essential
      - dkms
      - xserver-xorg-core
      - xserver-xorg-video-vmware
      - xserver-xorg-input-evdev
      - x11-xserver-utils
      - x11-xkb-utils
      - x11-utils
      - xinit
      - dmenu