- name: "Install JetBrainsMono Nerd font"
  become: true
  copy:
    src: "{{ playbook_dir }}/roles/fonts/files/JetBrainsMono"
    dest: "/usr/share/fonts/truetype/"

- name: "Install fontconfig"
  become: true
  ansible.builtin.apt:
    name: fontconfig

- name: "Install fonts from apt"
  become: true
  ansible.builtin.apt:
    name:
      - fonts-noto

- name: "Cache fonts"
  shell: |
    fc-cache -fv